### ISSUE TITLE
[Bug]: Ripple click effect applies on whole page in table mode

### ISSUE THREAD

**Issue by asrevni** [VueTorrent/VueTorrent#1816] opened 2024-08-01 10:26 UTC
### Bug description

The effect of selecting an item in table mode has a wrong anchor point in Safari for iOS and macOS.

![Screenshot 2024-07-31 at 7 13 47 PM](https://github.com/user-attachments/assets/c81ccd64-277d-437d-92ff-c3bf80f313f0)

### Expectations

The effect should be contained within items' area.

### Relevant debug informations

```shell
In Chrome works fine.
```

### Steps to reproduce

1. Open VueTorrent in Safari for iOS/macOS.
2. Select table mode.
3. Click on an item.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: macOS 13.6.3

PWA: Yes
Running inside a container: No
```

### qBittorrent version

4.6.5

### VueTorrent version

2.11.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment] 2024-08-04 16:31
I'd say that everything's good as it works on other browser. It may be a vuetify bug where they don't handle safari properly.

Unable to reproduce as I don't have Apple devices ATM.

**Comment by nathanuphoff** [comment] 2024-08-16 16:02
This is caused because safari [does not support](https://mtsknn.fi/blog/relative-tr-in-safari/) `position: relative` on a `tr` element so the absolute positioning of the ripple effect is unconstrained to it’s boundaries. I applied a bandaid fix for this myself by adding the following css snippet to my safari user `Style sheet`, found in `Settings...` -> `Advanced`:
```css
html:has(link[rel=stylesheet][href*="<domain>"]) tr .v-ripple__container {
  display: none!important;
}
```

**Comment by Larsluph** [comment] 2024-08-16 16:46
Also got a response from Vuetify: vuetifyjs/vuetify#20310

I can add the rule mentioned above if it has been tested.

**Comment by asrevni** [comment] 2024-08-16 17:15
Adding this css snippet makes the ripple effect work as intended.

`tr {
  transform: translate(0);
  clip-path: inset(0);
}`

**Comment by Larsluph** [comment] 2024-08-16 17:49
Here's the build for assessment. Let me know if it's good.

[vuetorrent.zip](https://github.com/user-attachments/files/16639928/vuetorrent.zip)

**Comment by asrevni** [comment] 2024-08-16 17:55
Yep, it's good! Thank you!

**Closed** 2024-08-16 18:46 UTC
Labels: Bug, Table View, Safari
