### ISSUE TITLE
[Bug]: Right-click on the item, copy->magnet, shows "Unable to copy, context isn't secured!"

### ISSUE THREAD

**Issue by amorlzu** [VueTorrent/VueTorrent#1801] opened 2024-07-22 02:51 UTC
### Bug description

Right-click on the item, copy->magnet, shows "Unable to copy, context isn't secured!"
If I return to the Qbittorrent default web UI, everything works normally.

### Expectations

Nope

### Relevant debug informations

```shell
This could be found in several qB - vuetorrent combinations,
I don't know when it appears, but I guess it may related to 2.x,
This issue appears once I upgrade to the new version(I cannot remember which version).
```

### Steps to reproduce

see Bug description

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Synology DSM 7.2.1-69057 Update5

PWA: Not sure
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.11.0

### Agreements

- [x] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment] 2024-07-22 03:46
Duplicate of #1414

**Closed by Larsluph** 2024-07-22 03:46 UTC
Labels: Bug, triage
