### ISSUE TITLE
[Bug]: The tag list in the right-click menu does not display all the tags in higher browser zoom levels

### ISSUE THREAD

**Issue by Nocifer** [VueTorrent/VueTorrent#1986] opened 2024-10-22 19:49 UTC
### Bug description

When the browser tab hosting Vuetorrent is zoomed high enough, the tag list in the right-click menu is cut short depending on the zoom level and resolution. E.g. with my default settings of 150% zoom @1440p in Firefox, the amount of tags shown is a hard 16 - any more than that and they are either not displayed at all, or white space is added at the end of the list, occupying the space that ought to be occupied by the missing tags.

Adding just one of the missing tags to a torrent restores the whole tag list (for that torrent only of course). The tag needs not be the last one, e.g. with a tag list of 20 tags, where only 16 tags show initially, adding the 17th tag to a torrent makes all 20 tags properly show up.

### Expectations

All tags should show in the right-click tag list regardless of if they're checked or not.

### Relevant debug informations

Happens in both Chrome and Firefox.

Also, I know that this may slighthly piss somebody off, but despite having checked the "Agreements" checkboxes below, I haven't tested with either the latest qB version (can't update it for the time being) or with the latest Vuettrrent nightly (I tried, but for some reason I only managed to completely bork my qB and was forced to restart it in order to fix it).

### Steps to reproduce

1. Open Vuetorrent.
2. Zoom the tab in.
3. Create a large number of tags; the exact number depends on the specific combination of zoom/resolution/scaling factor/etc, e.g. in my 1440p screen with 150% zoom and scaling factor of 1.0, anything over 16 tags will produce the issue.
4. Right-click on a torrent and try to scroll to the bottom of the tag list.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: Arch Linux
Browser (name and version): Firefox 131, Chromium 130

PWA: No
Running inside a container: qB yes, Vuetorrent no
```

### qBittorrent version

4.6.5

### VueTorrent version

2.15.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment] 2024-10-22 21:33
Please attach a screenshot of the bug, it probably already got fixed earlier today in #1985

**Comment by Nocifer** [comment] 2024-10-23 08:39
Yeah, it sure sound like the same bug; I even noticed some buggy whitespace in the Categories list as well, so it's definitely not a Tags only thing. A real shame that I couldn't test with the nightly...

But anyway, screenshots:

1. No tags applied, 21 tags in total, list not scrolled, extra whitespace at the bottom.
https://ibb.co/4Kf2SRY

2. No tags applied, 21 tags in total, list scrolled to the bottom, list ends at tag 20.
https://ibb.co/Bqbc71n

3. Tag 1 applied, list not scrolled, no more whitespace at the bottom.
https://ibb.co/d4V4Wc9

4. Tag 1 applied, list scrolled to the bottom, all 21 tags now show properly.
https://ibb.co/j435c6M

**Comment by Larsluph** [comment] 2024-10-23 20:39
I saw in my tests that having a list of 20-22 elements causes this particular problem on regular-sized screens so it is already fixed with #1985

**Comment by Larsluph** [comment] 2024-10-23 20:40
I can take a look at the active filter chip but it's mainly handled by vuetify, not sure I can do much about it...

**Closed by Larsluph** 2024-10-23 20:39 UTC
Labels: Bug, triage

**Comment by Larsluph** [comment] 2024-10-23 22:01
Unable to reproduce after trying a few way to not trigger the blur event, the chip menu collapses as soon as the mouse goes back in the page.

**Comment by Nocifer** [comment] 2024-10-24 08:34
I believe I have found a way to reliably reproduce it, but since this report is now closed, I'll just open a new bug report for it.
