### ISSUE TITLE
[Feature Request]: can not copy magnet link without https

### ISSUE THREAD

**Issue by ChenDY2233** [VueTorrent/VueTorrent#1764] opened 2024-06-29 04:46 UTC
### Description

![image](https://github.com/VueTorrent/VueTorrent/assets/39426660/8d6b74a4-16c8-4ab7-b42b-dc7102282ef6)

### Describe the solution you'd like

if i want to copy magnet link in vuetorrent, make qbittorrent support https is the only way ???

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment] 2024-06-29 05:42
This is a browser limitation. We can't do anything about it.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

> **Secure context**: This feature is available only in [**secure contexts**](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [**supporting browsers**](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility).

**Comment by Larsluph** [comment] 2024-06-29 05:43
Duplicate of #1414

**Closed by Larsluph** 2024-06-29 05:42 UTC
Labels: Feature, triage
