### ISSUE TITLE
[Feature Request]: Bulk Rename Files

### ISSUE THREAD

**Issue by khatharsis42** [VueTorrent/VueTorrent#1707] opened 2024-05-28 07:59 UTC
### Description

It'd be really nice to be able to bulk rename files or folders ! Apparently it's already in the original WebUI since recently (https://github.com/qbittorrent/qBittorrent/pull/18287)

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment] 2024-05-28 09:12
Already done in v2.8.0
Duplicate of #895

**Closed by Larsluph** 2024-05-28 09:12 UTC
Labels: Feature, triage
