### ISSUE TITLE
[Bug]: When deleting a torrent the checkbox "delete files with torrent" won't check

### ISSUE THREAD

**Issue by moracha** [VueTorrent/VueTorrent#1960] opened 2024-10-09 05:12 UTC
### Bug description

![firefox_2024-10-08_21-54-18](https://github.com/user-attachments/assets/28fa5bd8-1098-4a12-b69d-59d771b41f40)

### Expectations

"Delete files with torrent" box not checking

### Relevant debug informations

Upgraded to 2.14.0 from 2.13.3 and this functionality seems to be lost from a recent change. Refreshing browser doesn't help. Same behavior on both Windows and Android versions of Firefox.

### Steps to reproduce

1. See screen cap

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Laptop / Phone
OS: Windows 11 / Android 13
Browser (name and version): Firefox 131
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment] 2024-10-09 06:18
Duplicate of #1951

**Closed by Larsluph** 2024-10-09 06:18 UTC
Labels: Bug, triage
