### ISSUE TITLE
[Bug]: files are not deleted along with the torrent

### ISSUE THREAD

**Issue by agevlakh** [VueTorrent/VueTorrent#1959] opened 2024-10-08 15:14 UTC
### Bug description

when deleting a torrent, there is no works check mark that allows you to delete torrent files

### Expectations

Check mark wokks for deleting torrent

### Relevant debug informations

![Screenshot_20241008-181142](https://github.com/user-attachments/assets/242930f7-90e6-4617-a697-232437a88d38)

### Steps to reproduce

1.choose torrent 
2. touch delete
3. Checkbox for delete files not working

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: (Desktop / Phone)
OS: (Windows / Android )
Browser (name and version): chrome 130

PWA: Yes / No
Running inside a container:  No
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment] 2024-10-08 15:46
Duplicate of #1951

**Closed** 2024-10-08 15:47 UTC
Labels: Bug, triage
