### ISSUE TITLE
[Bug]: Sort by name not working

### ISSUE THREAD

**Issue by agevlakh** [VueTorrent/VueTorrent#1783] opened 2024-07-09 05:31 UTC
### Bug description

Hello.  When I try to sort by name, sorting by name does not work, everything is in an illogical order.  also nothing changes when I click on the arrow to change the sort direction.  version 2.9.0 does not have this problem.

### Expectations

I expect torrents to be sorted by name.  and the reverse sort functionality will also work

### Relevant debug informations

```shell
this bug appears in version 2.10.2, but is not present in 2.9.0.  I also have Russian in the vuetorrent settings and there are torrent names in English and Russian.
```

### Steps to reproduce

1. Update to 2.10.2
2. enable sorting of torrents by name
3. make sure that sorting is not working and the reverse sort arrow button does not work

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: PC Server ASRock N100M
OS: Freebsd 14.1 p2

PWA: Yes / No ?
Running inside a container: No
```

### qBittorrent version

4.6.5

### VueTorrent version

2.10.2

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by agevlakh** [comment] 2024-07-09 05:33
![IMG_20240709_082130_998](https://github.com/VueTorrent/VueTorrent/assets/105754474/6e708871-a773-440a-bd76-63c11cff7336)
Bug presents

**Comment by Larsluph** [comment] 2024-07-09 06:08
Duplicate of #1768

It will be fixed in the next release.

**Closed** 2024-07-09 07:20 UTC
Labels: Bug, triage
