### ISSUE TITLE
[Bug]: Can't check "delete" box + files are deleted anyway on removal

### ISSUE THREAD

**Issue by ClementNerma** [VueTorrent/VueTorrent#1964] opened 2024-10-11 12:58 UTC
### Bug description

I've recently created a new stack using the [repository's Docker-Compose file](https://github.com/VueTorrent/VueTorrent/blob/master/docker-compose.yml).

I've had some troubles setting it up (it started by saying `Unacceptable file type, only regular file is allowed.` and I needed to disable the mod, change the WebUI's settings, then add it back) but it ended up working.

I only have one problem right now: when I remove a torrent, I'm unable to check the delete box:

![image](https://github.com/user-attachments/assets/88c3758d-faa8-48aa-8d41-73aad4f1d640)

Whenever I click on it, there is the usual little animation on a checkbox, but it's not checked. And when I press the "DELETE" button, the torrent is removed but the file as well! It's put in the `.Trash-1000` directory. This happens even if I didn't try to click the checkbox.

### Expectations

1. The checkbox should be togglable
2. Files shouldn't be deleted when the checkbox isn't checked

### Relevant debug informations

I don't think it's related, but when I open the WebUI I get the following errors in the console:

![image](https://github.com/user-attachments/assets/3a6c14cb-32a3-4c3a-a638-3f1845fdb1a2)

The message in french tells that the `Same Origin` policy doesn't allow to read the remote resource located on `http://ipinfo.io/...`

### Steps to reproduce

1. Download the repository's `docker-compose.yml` file
2. Remove the mod from the compose file
3. Run `docker compose up -d`
4. Go the WebUI's settings and make it point to VueTorrent's directory
5. Add the mod back
6. Run `docker compose up -d` again to re-create the container
7. Download a torrent
8. Try to delete it

### How did you install VueTorrent?

Other (specify in env description)

### Environment description

```plain text
Device type: Headless server
OS: Server is on Ubuntu 24.04, kernel 6.8.0-40-generic, client is on Windows 23H2 build 22631
Browser (name and version): Firefox Developer Editino 132.0b5 (64 bits)
PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment] 2024-10-11 14:40
Duplicate of #1951

Bug has been fixed in 2.14.1

**Closed by Larsluph** 2024-10-11 14:40 UTC
Labels: Bug, triage
