### ISSUE TITLE
[Bug]: AddTorrent: The value of "Download Path (incomplete torrents)" is always implemented automatically by default even when  the option is diabled from global settings.

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1465] opened 2024-01-17 03:32 UTC
### Bug description

Env:
VueTorrent: 2.5.0
qBittorrent: 4.6.2
Browser: Microsoft New Edge

Steps:
1. Disable the "Default Download Path (incomplete torrents)" from qB global settings. Save.
2.  Add Torrent.
3. Check the value of "Download Path (incomplete torrents)".

Result:
The value of "Download Path (incomplete torrents)" is always implemented automatically even when  the option is diabled from global settings.

Notes:
For users who disabled this option, normally they don't hope the torrents will be downloaded to a different path during the downloading. 
If this field is always implemented automatically by default in this case, users have to delete the value of it every time when adding a new torrent.

Settings:
![downloadpathoption](https://github.com/VueTorrent/VueTorrent/assets/13391232/80127505-f4bb-49ff-a4bb-37ff41f04cf8)

Adding a new torrent:
![AddTorrents](https://github.com/VueTorrent/VueTorrent/assets/13391232/592825b4-2467-4a50-9d91-76d9e175383b)

### Expectations

Expected:
The value of "Download Path (incomplete torrents)" should be empty or null by default.
Because this option is already disabled by qB global settings.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: PC
OS: Win11

Running inside a container: No
```

### qBittorrent version

4.6.2

### VueTorrent version

2.5.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment] 2024-03-28 15:56
Duplicate of #1372

**Closed** 2024-03-28 15:56 UTC
Labels: Bug
