### ISSUE TITLE
Add bulk rename feature

### ISSUE THREAD

**Issue by ticklemyIP** [VueTorrent/VueTorrent#895] opened 2023-06-23 20:36 UTC
This is something this project could be unique in. There's currently no known way (by me) of bulk renaming torrents' files "in house" (through the torrent software). Why this would be preferred as opposed to regular renaming, is a user wouldn't always be able to (or want to) ssh into a box or (in a better situation) open a file manager, or use a different crappy bulk renamer. And also this way the torrent sooftware wouldn't find the new and renamed file wich would disable seeding or downloading.

This feature would be most useful with mediaservers which often use a very strict naming scheme in order to recognize media and apply metadata, which torrent uploaders doesn't always follow. This is particularly true with shows, thus bulk renaming would be a much better way of managing these files.

**Comment by Larsluph** [comment] 2023-06-23 22:55
Duplicate of #752 ?

**Comment by ticklemyIP** [comment] 2023-06-23 22:58
Could be, but I think my issue is a bit more detailed and gives better reasons. Up to you which one you want to keep of course.

**Comment by gpollo** [comment] 2023-07-27 17:07
In [killemov/Shift](https://github.com/killemov/Shift) custom UI for Transmission, the batch rename simply uses Regex patterns.

A UI as simple this could work very well.

```
+--------------------------------------+
|                                      |
| Pattern:     $tv.show.(S..E..)*.mkv^ |
|                                      |
| Replacement: TV Show - \1.mkv        |
|                                      |
|                                Apply |
+--------------------------------------+
```

If I have time, I may have a look at implementing that.

**Comment by loligans** [comment] 2024-03-29 16:14
I also implemented this functionality in the main qBittorrent WebUI here: https://github.com/qbittorrent/qBittorrent/pull/18287

**Comment by Larsluph** [comment] 2024-04-12 05:51
Fixed with 1624

**Closed** 2024-04-12 05:51 UTC
Labels: Content Tab, Torrent Management
