### ISSUE TITLE
[Feature Request]: Disabling coloring option

### ISSUE THREAD

**Issue by zip6como** [VueTorrent/VueTorrent#1603] opened 2024-03-24 19:27 UTC
### Description

Hi,

I just downloaded the 2.7.2 update of VueTorrent.
I saw the new coloring of Category, Tags and Ratio.
I personally dislike the (random) coloring and would like to disable it and go back to the coloring from V2.7.1.

### Describe the solution you'd like

An option to go back to the old coloring in the settings of VueTorrent.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment] 2024-03-24 19:36
Duplicate of #1593

**Closed by Larsluph** 2024-03-24 19:36 UTC
Labels: Feature, triage
