### ISSUE TITLE
[Feature Request]: Using the enhanced version of qBittorrent, I hope an option can be added.

### ISSUE THREAD

**Issue by AbcdefgXW** [VueTorrent/VueTorrent#1709] opened 2024-06-01 18:59 UTC
### Description

"I hope an option for the enhanced version can be added to automatically subscribe to tracker links. This option is not currently displayed in this version, and I always have to switch back to the default UI to set it up."

### Complementary informations

- [x] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment] 2024-06-01 19:14
Please describe your issue in English or it will be closed.

**Comment by AbcdefgXW** [comment] 2024-06-01 19:34
> Please describe your issue in English or it will be closed.

"Okay, got it. The issue has been revised."

**Comment by Larsluph** [comment] 2024-06-02 08:42
Duplicate of #867

**Closed by Larsluph** 2024-06-02 08:42 UTC
Labels: Feature, triage

**Comment by AbcdefgXW** [comment] 2024-06-02 09:44
> Duplicate of #867

v4.6.4.10
